### ISSUE TITLE
Message status - Version 2

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/sso#10]
![image](https://user-images.githubusercontent.com/44457418/212270824-6e4e5ef7-9141-4e18-b721-94744adef1f9.png)
Design at 
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=552%3A1816&t=h8aObSmTfUsu9fNt-0

**Comment by thaoredweb** [comment]
Moved to https://github.com/aesirxio/sso-template/issues/7
