### ISSUE TITLE
There's nothing happen when connecting to Concodium

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/sso#13]
1. Go to demo site https://demo.dma.aesirx.io/login
2. Login with Concordium btn

Actual output:
Nothing happen after connect to Concordium wallet

**Comment by huynhngocgiau** [comment]
Unable to connect, show messege "Your wallet is not regstered"

![Image](https://user-images.githubusercontent.com/79819354/212226761-3fbb1708-44f7-4135-83a0-47ed7b50cb16.png)



![Image](https://user-images.githubusercontent.com/79819354/212226771-01a8259d-7a61-4398-9a60-e7d130f8fb07.png)
