### ISSUE TITLE
Nothing happen when connect to SSO with Metamask

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/sso#15]
1. Sign up with Metamask wallet
2. Go to dma demo site to login
3. After connect successfully, it show nothing
![meta1](https://user-images.githubusercontent.com/30283123/211704283-64498ca4-a154-4e9f-a066-8052a2a57c7b.png)

**Comment by huynhngocgiau** [comment]
![image](https://user-images.githubusercontent.com/79819354/211719169-0b12d0ef-c8e8-4789-8332-b258955d84bb.png)

**Comment by huynhngocgiau** [comment]
I checked, it's working
