### ISSUE TITLE
The page load ever when I cancel

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/sso#19]
1. Sign up with Web2 authen
2. Sign in to https://demo.pim.aesirx.io/ 
3. Click on Cancel button
Actual output:
The page loads ever
Expected output:
Close and turn of the pop up
![sso_pim](https://user-images.githubusercontent.com/30283123/211787079-b2c35f06-a0fe-4e4f-8cb4-25b341e99b8e.png)

**Comment by vietredweb** [comment]
It worked now chị @thaoredweb
