### ISSUE TITLE
Missing MetaMask connect button

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/sso#23]
1. Login to DMA and connect to MetaMask wallet on Firefox. It will create an address wallet
2. Turn off the browser. Open another browser: Chrome
3. Go to https://demo.sso.aesirx.io/ site on , click on "Sign in with SSO". Page opens a pop up

Actual output:
Missing MetaMask connect button
![MetaMask](https://user-images.githubusercontent.com/30283123/213356517-82636d33-845f-4a15-a0b8-b4c9a6f34957.PNG)

**Comment by Walletsuppport** [comment]
> 1. Login to DMA and connect to MetaMask wallet on Firefox. It will create an address wallet
> 2. Turn off the browser. Open another browser: Chrome
> 3. Go to https://demo.sso.aesirx.io/ site on , click on "Sign in with SSO". Page opens a pop up
> 
> Actual output:
> Missing MetaMask connect button
> ![MetaMask](https://user-images.githubusercontent.com/30283123/213356517-82636d33-845f-4a15-a0b8-b4c9a6f34957.PNG)
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Walletsuppport** [comment]
> 1. Login to DMA and connect to MetaMask wallet on Firefox. It will create an address wallet
> 2. Turn off the browser. Open another browser: Chrome
> 3. Go to https://demo.sso.aesirx.io/ site on , click on "Sign in with SSO". Page opens a pop up
> 
> Actual output:
> Missing MetaMask connect button
> ![MetaMask](https://user-images.githubusercontent.com/30283123/213356517-82636d33-845f-4a15-a0b8-b4c9a6f34957.PNG)
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
