### ISSUE TITLE
Add specific wallet requests to the SSO configuration

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/sso#30]
Make sure that SSO can request specific wallet login using:

* Metamask
* Concordium

So basically and in the configuration, you will be able to require a user to login using some specific wallet and hide a regular login.

**Comment by shandak** [comment]
@jatitoam what if I made 3 options: Metamask, Concordium, and Regular login depending on flags it will show related login ways?

**Comment by shandak** [comment]
related code: 
https://github.com/aesirxio/sso-template/pull/25
https://github.com/aesirxio/sso/pull/40

**Comment by jatitoam** [comment]
Yes, that's fine @shandak
